require('dotenv').config({ path: '.env.local' })
const { createClient } = require('@supabase/supabase-js')

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

if (!supabaseUrl || !supabaseAnonKey) {
  console.error('❌ Missing Supabase environment variables!')
  console.error('Please ensure NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY are set in your .env.local file')
  process.exit(1)
}

const supabase = createClient(supabaseUrl, supabaseAnonKey)

// Complete tools array with id fields removed
const tools = [
  {
    name: "Sherlock",
    description: "Hunt down social media accounts by username across 400+ social networks. This tool searches for usernames across social networks and websites, making it essential for finding all online accounts associated with a specific username during investigations.",
    category: "Username",
    status: "online",
    url: "https://github.com/sherlock-project/sherlock",
    pricing: "Free",
    registration: false,
  },
  {
    name: "WhatsMyName",
    description: "Username enumeration tool that checks for username availability across multiple platforms. It helps investigators find social media accounts and online presence associated with specific usernames across various websites and services.",
    category: "Username",
    status: "online",
    url: "https://whatsmyname.app/",
    pricing: "Free",
    registration: false,
  },
  {
    name: "Namechk",
    description: "Check username and domain availability across hundreds of social networks and domain extensions. This tool is useful for brand monitoring and finding available usernames across multiple platforms simultaneously.",
    category: "Username",
    status: "online",
    url: "https://namechk.com/",
    pricing: "Free",
    registration: false,
  },
  {
    name: "Social Searcher",
    description: "Real-time social media search engine and monitoring tool. Search for content across multiple social media platforms simultaneously, useful for monitoring mentions, tracking hashtags, and gathering social media intelligence.",
    category: "Social Media",
    status: "online",
    url: "https://www.social-searcher.com/",
    pricing: "Freemium",
    registration: true,
  },
  {
    name: "Twint",
    description: "Advanced Twitter scraping tool that works without using Twitter's API. Gather tweets, followers, and other Twitter data without API limitations, particularly useful for social media investigations and sentiment analysis projects.",
    category: "Social Media",
    status: "offline",
    url: "https://github.com/twintproject/twint",
    pricing: "Free",
    registration: false,
  },
  {
    name: "IntelTechniques",
    description: "Comprehensive collection of OSINT tools and custom search engines for social media investigation. Created by Michael Bazzell, this platform provides specialized search tools for various social media platforms and online services.",
    category: "Social Media",
    status: "online",
    url: "https://inteltechniques.com/tools/",
    pricing: "Free",
    registration: false,
  },
  {
    name: "theHarvester",
    description: "Gather emails, subdomains, hosts, employee names from public sources. Uses multiple search engines and data sources to collect information about a target domain, essential for reconnaissance and information gathering phases.",
    category: "Email",
    status: "online",
    url: "https://github.com/laramies/theHarvester",
    pricing: "Free",
    registration: false,
  },
  {
    name: "Have I Been Pwned",
    description: "Check if email addresses have been compromised in data breaches. Search across multiple data breaches to see if an email address has been compromised, crucial for security assessments and personal security awareness.",
    category: "Email",
    status: "online",
    url: "https://haveibeenpwned.com/",
    pricing: "Freemium",
    registration: false,
  },
  {
    name: "Hunter.io",
    description: "Find and verify professional email addresses associated with any website or company. This tool helps locate contact information for businesses and individuals, useful for outreach and investigation purposes.",
    category: "Email",
    status: "online",
    url: "https://hunter.io/",
    pricing: "Freemium",
    registration: true,
  },
  {
    name: "Holehe",
    description: "Check if an email address is attached to an account on over 120 websites. This tool helps investigators determine which services an email address is registered with, useful for account enumeration and investigation.",
    category: "Email",
    status: "online",
    url: "https://github.com/megadose/holehe",
    pricing: "Free",
    registration: false,
  },
  {
    name: "Shodan",
    description: "Search engine for Internet-connected devices and services. Crawls the internet to find and index devices like webcams, routers, servers, and IoT devices, invaluable for security researchers and penetration testers.",
    category: "Network",
    status: "online",
    url: "https://www.shodan.io/",
    pricing: "Freemium",
    registration: true,
  },
  {
    name: "Censys",
    description: "Search engine for finding and analyzing Internet-connected devices. Provides detailed information about hosts and websites across the internet, offering more detailed analysis than basic port scanners for security research.",
    category: "Network",
    status: "online",
    url: "https://censys.io/",
    pricing: "Freemium",
    registration: true,
  },
  {
    name: "Nmap",
    description: "Network discovery and security auditing tool. Industry standard for network reconnaissance and security scanning, can discover hosts, services, operating systems, and vulnerabilities across networks.",
    category: "Network",
    status: "online",
    url: "https://nmap.org/",
    pricing: "Free",
    registration: false,
  },
  {
    name: "Masscan",
    description: "High-speed port scanner capable of scanning the entire Internet in under 6 minutes. Designed for large-scale network reconnaissance and security assessments, particularly useful for discovering open ports across large IP ranges.",
    category: "Network",
    status: "online",
    url: "https://github.com/robertdavidgraham/masscan",
    pricing: "Free",
    registration: false,
  },
  {
    name: "WhoisXML API",
    description: "Domain and IP address WHOIS lookup and research tools. Provides comprehensive domain registration data, DNS records, and historical WHOIS information essential for investigating domain ownership and registration patterns.",
    category: "Domains",
    status: "online",
    url: "https://whoisxmlapi.com/",
    pricing: "Freemium",
    registration: true,
  },
  {
    name: "DNSdumpster",
    description: "Free domain research tool that discovers hosts related to a domain. Provides DNS reconnaissance and mapping, helping investigators understand the infrastructure and subdomains associated with a target domain.",
    category: "Domains",
    status: "online",
    url: "https://dnsdumpster.com/",
    pricing: "Free",
    registration: false,
  },
  {
    name: "Sublist3r",
    description: "Subdomain enumeration tool designed to enumerate subdomains using OSINT. Gathers subdomains from various sources including search engines, helping map out the complete infrastructure of a target domain.",
    category: "Domains",
    status: "online",
    url: "https://github.com/aboul3la/Sublist3r",
    pricing: "Free",
    registration: false,
  },
  {
    name: "SecurityTrails",
    description: "Historical DNS data and domain intelligence platform. Provides comprehensive DNS history, subdomain discovery, and domain monitoring capabilities for security research and threat intelligence.",
    category: "Domains",
    status: "online",
    url: "https://securitytrails.com/",
    pricing: "Freemium",
    registration: true,
  },
  {
    name: "Pipl",
    description: "People search engine for finding personal information. Searches deep web sources and public records to find comprehensive information about individuals, effective for finding contact information and social media profiles.",
    category: "People",
    status: "online",
    url: "https://pipl.com/",
    pricing: "Paid",
    registration: true,
  },
  {
    name: "TruePeopleSearch",
    description: "Free people search engine providing access to public records. Find contact information, addresses, phone numbers, and associated individuals using publicly available data sources.",
    category: "People",
    status: "online",
    url: "https://www.truepeoplesearch.com/",
    pricing: "Free",
    registration: false,
  },
  {
    name: "FastPeopleSearch",
    description: "Quick people search tool for finding personal information from public records. Provides addresses, phone numbers, and associated individuals, useful for background research and contact information discovery.",
    category: "People",
    status: "online",
    url: "https://www.fastpeoplesearch.com/",
    pricing: "Free",
    registration: false,
  },
  {
    name: "Spokeo",
    description: "People search engine that aggregates public records and social media information. Provides comprehensive profiles including contact information, social media accounts, and background information.",
    category: "People",
    status: "online",
    url: "https://www.spokeo.com/",
    pricing: "Freemium",
    registration: true,
  },
  {
    name: "TinEye",
    description: "Reverse image search engine to find where images appear online. Helps investigators track the origin and usage of images across the web, useful for verifying image authenticity and finding higher resolution versions.",
    category: "Images",
    status: "online",
    url: "https://tineye.com/",
    pricing: "Freemium",
    registration: false,
  },
  {
    name: "Google Images",
    description: "Google's reverse image search functionality. Upload or paste image URLs to find similar images, identify objects, and discover where images appear online, integrated into Google's search ecosystem.",
    category: "Images",
    status: "online",
    url: "https://images.google.com/",
    pricing: "Free",
    registration: false,
  },
  {
    name: "Yandex Images",
    description: "Yandex's reverse image search engine, often more effective than Google for certain types of images. Particularly good at facial recognition and finding images from Eastern European and Russian sources.",
    category: "Images",
    status: "online",
    url: "https://yandex.com/images/",
    pricing: "Free",
    registration: false,
  },
  {
    name: "Jeffrey's Image Metadata Viewer",
    description: "Online tool for extracting and viewing EXIF data from images. Reveals camera settings, GPS coordinates, timestamps, and other metadata that can be crucial for image analysis and verification.",
    category: "Images",
    status: "online",
    url: "http://exif.regex.info/exif.cgi",
    pricing: "Free",
    registration: false,
  },
  {
    name: "GeoSpy",
    description: "AI-powered geolocation tool that can identify locations from images. Uses machine learning to analyze visual clues in photographs to determine where they were taken, useful for image verification and investigation.",
    category: "Geolocation",
    status: "online",
    url: "https://geospy.web.app/",
    pricing: "Free",
    registration: false,
  },
  {
    name: "What3Words",
    description: "Location reference system that divides the world into 3m x 3m squares, each with a unique three-word address. Useful for precise location identification and sharing coordinates in an easy-to-remember format.",
    category: "Geolocation",
    status: "online",
    url: "https://what3words.com/",
    pricing: "Free",
    registration: false,
  },
  {
    name: "GeoGuessr",
    description: "Geography game that can be used for location training and geolocation skills development. While primarily a game, it's useful for training investigators to recognize geographical features and locations.",
    category: "Geolocation",
    status: "online",
    url: "https://www.geoguessr.com/",
    pricing: "Freemium",
    registration: true,
  },
  {
    name: "Wayback Machine",
    description: "View archived versions of websites from the past. The Internet Archive's tool stores billions of web pages over time, essential for seeing how websites looked in the past and recovering deleted content.",
    category: "Archive Tools",
    status: "online",
    url: "https://web.archive.org/",
    pricing: "Free",
    registration: false,
  },
  {
    name: "Archive.today",
    description: "Website archiving service that creates permanent snapshots of web pages. Useful for preserving evidence and accessing content that may have been removed or modified since original publication.",
    category: "Archive Tools",
    status: "online",
    url: "https://archive.today/",
    pricing: "Free",
    registration: false,
  },
  {
    name: "CachedView",
    description: "Access cached versions of websites from Google, Bing, and other search engines. Provides multiple sources for viewing previously indexed versions of web pages when current versions are unavailable.",
    category: "Archive Tools",
    status: "online",
    url: "http://cachedview.com/",
    pricing: "Free",
    registration: false,
  },
  {
    name: "FOCA",
    description: "Find metadata and hidden information in documents. Analyzes documents found on web pages and extracts valuable metadata that can reveal information about software used, usernames, and folder paths.",
    category: "Documents",
    status: "warning",
    url: "https://github.com/ElevenPaths/FOCA",
    pricing: "Free",
    registration: false,
  },
  {
    name: "Metagoofil",
    description: "Extract metadata from public documents found on target websites. Searches for and downloads documents from target websites, then extracts metadata that can reveal internal network information.",
    category: "Documents",
    status: "warning",
    url: "https://github.com/laramies/metagoofil",
    pricing: "Free",
    registration: false,
  },
  {
    name: "DocumentCloud",
    description: "Platform for analyzing, annotating, and publishing documents. Provides tools for document analysis, OCR, and collaborative investigation, particularly useful for investigative journalism and research.",
    category: "Documents",
    status: "online",
    url: "https://www.documentcloud.org/",
    pricing: "Free",
    registration: true,
  },
  {
    name: "Maltego",
    description: "Interactive data mining tool for link analysis and data visualization. Provides a graphical interface for analyzing relationships between people, companies, domains, and other entities for complex relationship mapping.",
    category: "Analysis",
    status: "online",
    url: "https://www.maltego.com/",
    pricing: "Freemium",
    registration: true,
  },
  {
    name: "Gephi",
    description: "Open-source network analysis and visualization software. Helps investigators visualize and analyze complex networks and relationships, particularly useful for social network analysis and data visualization.",
    category: "Analysis",
    status: "online",
    url: "https://gephi.org/",
    pricing: "Free",
    registration: false,
  },
  {
    name: "Palantir Gotham",
    description: "Enterprise data analysis platform for large-scale investigations. Integrates multiple data sources and provides advanced analytics capabilities for complex investigations and intelligence analysis.",
    category: "Analysis",
    status: "online",
    url: "https://www.palantir.com/platforms/gotham/",
    pricing: "Paid",
    registration: true,
  },
  {
    name: "Recon-ng",
    description: "Full-featured reconnaissance framework with modular design. Provides a powerful environment for conducting open-source web-based reconnaissance with independent modules and database interaction.",
    category: "Reconnaissance",
    status: "online",
    url: "https://github.com/lanmaster53/recon-ng",
    pricing: "Free",
    registration: false,
  },
  {
    name: "SpiderFoot",
    description: "Automated OSINT collection tool for reconnaissance and threat intelligence. Automates the process of gathering intelligence about a given target, integrating with multiple data sources for comprehensive scans.",
    category: "Automation",
    status: "offline",
    url: "https://www.spiderfoot.net/",
    pricing: "Freemium",
    registration: false,
  },
  {
    name: "Amass",
    description: "In-depth attack surface mapping and asset discovery tool. Performs network mapping of attack surfaces and external asset discovery using open source information gathering and active reconnaissance techniques.",
    category: "Reconnaissance",
    status: "online",
    url: "https://github.com/OWASP/Amass",
    pricing: "Free",
    registration: false,
  },
  {
    name: "VirusTotal",
    description: "Free online service that analyzes files and URLs for malicious content. Aggregates results from multiple antivirus engines and website scanners, essential for malware analysis and threat intelligence.",
    category: "Threat Intelligence",
    status: "online",
    url: "https://www.virustotal.com/",
    pricing: "Freemium",
    registration: true,
  },
  {
    name: "AlienVault OTX",
    description: "Open threat intelligence community platform. Provides access to threat data from security researchers worldwide, including indicators of compromise, attack patterns, and threat intelligence feeds.",
    category: "Threat Intelligence",
    status: "online",
    url: "https://otx.alienvault.com/",
    pricing: "Free",
    registration: true,
  },
  {
    name: "ThreatCrowd",
    description: "Search engine for threats that provides context and connections between indicators. Helps analysts understand relationships between domains, IPs, email addresses, and file hashes in threat investigations.",
    category: "Threat Intelligence",
    status: "online",
    url: "https://www.threatcrowd.org/",
    pricing: "Free",
    registration: false,
  },
  {
    name: "Hybrid Analysis",
    description: "Free malware analysis service powered by Falcon Sandbox. Provides detailed analysis reports for suspicious files and URLs, including behavioral analysis and threat intelligence indicators.",
    category: "Threat Intelligence",
    status: "online",
    url: "https://www.hybrid-analysis.com/",
    pricing: "Free",
    registration: true,
  },
  {
    name: "Bellingcat's Auto Archiver",
    description: "AI-powered tool for automatically archiving social media content. Uses machine learning to identify and preserve important content from social media platforms for investigative purposes.",
    category: "AI-Powered Tools",
    status: "online",
    url: "https://github.com/bellingcat/auto-archiver",
    pricing: "Free",
    registration: false,
  },
  {
    name: "FaceCheck.ID",
    description: "AI-powered reverse face search engine. Uses facial recognition technology to find images of people across the internet, useful for identity verification and investigation purposes.",
    category: "AI-Powered Tools",
    status: "online",
    url: "https://facecheck.id/",
    pricing: "Freemium",
    registration: true,
  },
  {
    name: "PimEyes",
    description: "AI-powered face search engine that finds faces across the internet. Uses advanced facial recognition to locate images of individuals across various websites and platforms.",
    category: "AI-Powered Tools",
    status: "online",
    url: "https://pimeyes.com/",
    pricing: "Freemium",
    registration: true,
  },
  {
    name: "Ahmia",
    description: "Search engine for Tor hidden services. Provides a way to search for content on the dark web while maintaining anonymity, useful for threat intelligence and cybercrime investigation.",
    category: "Dark Web Search",
    status: "online",
    url: "https://ahmia.fi/",
    pricing: "Free",
    registration: false,
  },
  {
    name: "DarkSearch",
    description: "Dark web search engine that indexes .onion sites. Provides search capabilities for Tor hidden services, helping investigators find relevant content on the dark web.",
    category: "Dark Web Search",
    status: "online",
    url: "https://darksearch.io/",
    pricing: "Free",
    registration: false,
  },
  {
    name: "OnionLand",
    description: "Search engine for Tor network hidden services. Indexes and provides search functionality for .onion sites, useful for dark web research and investigation.",
    category: "Dark Web Search",
    status: "online",
    url: "https://onionlandsearchengine.com/",
    pricing: "Free",
    registration: false,
  },
  {
    name: "Blockchain.info",
    description: "Bitcoin blockchain explorer and wallet service. Provides detailed information about Bitcoin transactions, addresses, and blocks, essential for cryptocurrency investigation and analysis.",
    category: "Digital Currency",
    status: "online",
    url: "https://www.blockchain.com/explorer",
    pricing: "Free",
    registration: false,
  },
  {
    name: "Etherscan",
    description: "Ethereum blockchain explorer and analytics platform. Provides comprehensive information about Ethereum transactions, smart contracts, and addresses for cryptocurrency investigation.",
    category: "Digital Currency",
    status: "online",
    url: "https://etherscan.io/",
    pricing: "Free",
    registration: false,
  },
  {
    name: "Crystal Blockchain",
    description: "Professional blockchain analytics platform for cryptocurrency investigation. Provides advanced tools for tracking cryptocurrency transactions and identifying suspicious activity.",
    category: "Digital Currency",
    status: "online",
    url: "https://crystalblockchain.com/",
    pricing: "Paid",
    registration: true,
  },
  {
    name: "Chainalysis",
    description: "Cryptocurrency investigation and compliance platform. Provides tools for tracking cryptocurrency transactions, identifying illicit activity, and ensuring regulatory compliance.",
    category: "Digital Currency",
    status: "online",
    url: "https://www.chainalysis.com/",
    pricing: "Paid",
    registration: true,
  },
  {
    name: "FlightRadar24",
    description: "Real-time flight tracking service showing aircraft movements worldwide. Provides detailed information about flights, aircraft, and airports, useful for transportation intelligence and investigation.",
    category: "Transportation Tracking",
    status: "online",
    url: "https://www.flightradar24.com/",
    pricing: "Freemium",
    registration: false,
  },
  {
    name: "MarineTraffic",
    description: "Global ship tracking intelligence platform. Provides real-time information about vessel movements, port activities, and maritime traffic worldwide for transportation investigation.",
    category: "Transportation Tracking",
    status: "online",
    url: "https://www.marinetraffic.com/",
    pricing: "Freemium",
    registration: false,
  },
  {
    name: "FlightAware",
    description: "Flight tracking and aviation data platform. Provides comprehensive flight information, aircraft tracking, and aviation analytics for transportation intelligence and investigation.",
    category: "Transportation Tracking",
    status: "online",
    url: "https://flightaware.com/",
    pricing: "Freemium",
    registration: false,
  },
  {
    name: "VesselFinder",
    description: "Ship tracking and maritime intelligence platform. Provides real-time vessel positions, port information, and maritime traffic data for shipping and transportation investigation.",
    category: "Transportation Tracking",
    status: "online",
    url: "https://www.vesselfinder.com/",
    pricing: "Freemium",
    registration: false,
  },
  {
    name: "CyberChef",
    description: "Web app for encryption, encoding, compression and data analysis. Provides a wide range of operations for data manipulation, decoding, and analysis, essential for digital forensics and investigation.",
    category: "Encoding/Decoding",
    status: "online",
    url: "https://gchq.github.io/CyberChef/",
    pricing: "Free",
    registration: false,
  },
  {
    name: "Base64 Decode",
    description: "Simple online tool for Base64 encoding and decoding. Useful for decoding Base64 encoded data commonly found in web applications, emails, and other digital communications.",
    category: "Encoding/Decoding",
    status: "online",
    url: "https://www.base64decode.org/",
    pricing: "Free",
    registration: false,
  },
  {
    name: "URL Decoder",
    description: "Online tool for URL encoding and decoding. Helps decode URL-encoded strings and parameters, useful for web application analysis and digital investigation.",
    category: "Encoding/Decoding",
    status: "online",
    url: "https://www.urldecoder.org/",
    pricing: "Free",
    registration: false,
  },
  {
    name: "Social Catfish",
    description: "Reverse search tool for dating profiles and social media accounts. Helps verify the authenticity of online dating profiles and identify potential catfish or fraudulent accounts.",
    category: "Dating Platforms",
    status: "online",
    url: "https://socialcatfish.com/",
    pricing: "Freemium",
    registration: true,
  },
  {
    name: "BeenVerified",
    description: "Background check service that includes social media and dating profile searches. Provides comprehensive background information including potential dating profiles and social media presence.",
    category: "Dating Platforms",
    status: "online",
    url: "https://www.beenverified.com/",
    pricing: "Paid",
    registration: true,
  },
  {
    name: "Creepy",
    description: "Geolocation OSINT tool for gathering location data from social media. Extracts geographical information from social media posts and photos to create location timelines for investigation purposes.",
    category: "Geolocation",
    status: "offline",
    url: "https://github.com/ilektrojohn/creepy",
    pricing: "Free",
    registration: false,
  },
  {
    name: "Wigle",
    description: "Wireless network mapping and wardriving database. Provides information about wireless access points and their locations, useful for geolocation and network investigation.",
    category: "Network",
    status: "online",
    url: "https://wigle.net/",
    pricing: "Free",
    registration: true,
  },
  {
    name: "Phonebook.cz",
    description: "Search engine for finding information about domains, URLs, and email addresses. Provides comprehensive search capabilities for various types of online information and digital footprints.",
    category: "Email",
    status: "online",
    url: "https://phonebook.cz/",
    pricing: "Free",
    registration: false,
  },
  {
    name: "Dehashed",
    description: "Database search engine for leaked credentials and data breaches. Provides access to compromised credentials from various data breaches for security research and investigation.",
    category: "Threat Intelligence",
    status: "online",
    url: "https://dehashed.com/",
    pricing: "Paid",
    registration: true,
  },
  {
    name: "Intelligence X",
    description: "Search engine and data archive for OSINT research. Provides access to various data sources including leaked databases, documents, and other intelligence information.",
    category: "Threat Intelligence",
    status: "online",
    url: "https://intelx.io/",
    pricing: "Freemium",
    registration: true,
  },
  {
    name: "Spyse",
    description: "Internet assets search engine for cybersecurity professionals. Provides comprehensive information about domains, IPs, certificates, and other internet infrastructure for security research.",
    category: "Network",
    status: "online",
    url: "https://spyse.com/",
    pricing: "Freemium",
    registration: true,
  },
  {
    name: "OSINT Framework",
    description: "Comprehensive collection of OSINT tools organized by category. Provides a structured approach to open source intelligence gathering with links to hundreds of useful tools and resources.",
    category: "Analysis",
    status: "online",
    url: "https://osintframework.com/",
    pricing: "Free",
    registration: false,
  },
  {
    name: "Hunchly",
    description: "Web capture tool designed for online investigations. Automatically captures and organizes web pages, images, and other content during investigations for evidence preservation and analysis.",
    category: "Analysis",
    status: "online",
    url: "https://www.hunch.ly/",
    pricing: "Paid",
    registration: true,
  },
  {
    name: "Lampyre",
    description: "Data analysis and visualization platform for investigations. Provides tools for analyzing large datasets, creating timelines, and visualizing relationships between entities in investigations.",
    category: "Analysis",
    status: "online",
    url: "https://lampyre.io/",
    pricing: "Freemium",
    registration: true,
  },
  {
    name: "Mitaka",
    description: "Browser extension for OSINT search from context menu. Allows quick searches across multiple OSINT tools directly from selected text in web browsers, streamlining investigation workflows.",
    category: "Analysis",
    status: "online",
    url: "https://github.com/ninoseki/mitaka",
    pricing: "Free",
    registration: false,
  },
  {
    name: "Sn1per",
    description: "Automated penetration testing framework with OSINT capabilities. Combines reconnaissance, vulnerability scanning, and exploitation in a single platform for comprehensive security assessments.",
    category: "Reconnaissance",
    status: "online",
    url: "https://github.com/1N3/Sn1per",
    pricing: "Freemium",
    registration: false,
  },
]

async function migrateTools() {
  console.log(`Starting migration of ${tools.length} tools...`)
  let success = 0
  let failed = 0

  for (const [i, tool] of tools.entries()) {
    try {
      const { error } = await supabase.from('tools').insert([tool])
      if (error) {
        failed++
        console.error(`❌ Tool ${i + 1}/${tools.length} (${tool.name}):`, error.message)
      } else {
        success++
        console.log(`✅ Tool ${i + 1}/${tools.length} (${tool.name}) inserted.`)
      }
    } catch (err) {
      failed++
      console.error(`❌ Tool ${i + 1}/${tools.length} (${tool.name}):`, err)
    }
  }

  console.log(`\nMigration complete. Success: ${success}, Failed: ${failed}`)
  process.exit(0)
}

migrateTools() 